# Generated by Django 5.0.6 on 2024-06-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegosMax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(upload_to='juegosMax/templates/juegosMax/assets/img/portadas'),
        ),
    ]
