# Generated by Django 5.0.6 on 2024-06-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegosMax', '0002_alter_juego_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
