# Generated by Django 5.0.6 on 2024-06-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegosMax', '0003_juego_available_juego_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
