# Generated by Django 5.0.6 on 2024-06-12 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegosMax', '0004_alter_juego_precio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userRegister',
        ),
    ]
