# Generated by Django 5.0.6 on 2024-06-13 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegosMax', '0008_alter_juego_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='imagen',
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_juegos/')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='juegosMax.juego')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos_juegos/')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='juegosMax.juego')),
            ],
        ),
    ]
