# Generated by Django 5.0.6 on 2024-06-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegosMax', '0009_remove_juego_imagen_imagen_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to='portadas/'),
        ),
    ]
