# Generated by Django 5.0.6 on 2024-06-14 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegosMax', '0010_alter_imagen_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos_juegos/')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos',
                                            to='juegosMax.juego')),
            ],
        ),
    ]
