# Generated by Django 5.0.6 on 2024-06-14 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegosMax', '0012_alter_video_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
