# Generated by Django 5.0.6 on 2024-06-14 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegosMax', '0013_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(default='')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailer', to='juegosMax.juego')),
            ],
        ),
    ]
