# Generated by Django 5.0.6 on 2024-06-14 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegosMax', '0014_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='juegosMax.juego'),
        ),
    ]
