# Generated by Django 5.0.6 on 2024-06-15 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegosMax', '0015_alter_trailer_juego'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='precio',
        ),
    ]
