# Generated by Django 5.0.6 on 2024-06-15 00:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegosMax', '0016_remove_juego_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='precio',
            field=models.CharField(default=1, max_length=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.RegexValidator('^\\d{1,3}(\\.\\d{3})*(\\,\\d{1,2})?$')]),
            preserve_default=False,
        ),
    ]
