# Generated by Django 5.0.6 on 2024-06-16 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegosMax', '0018_juego_descripcionextensa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='juego',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
