# Generated by Django 5.0.6 on 2024-06-16 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegosMax', '0020_carrito_itemcarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='precio',
        ),
    ]
