# Generated by Django 5.0.6 on 2024-06-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegosMax', '0021_remove_juego_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='precioClp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
