# Generated by Django 5.0.6 on 2024-06-16 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegosMax', '0022_juego_precioclp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='precioClp',
        ),
    ]
