# Generated by Django 5.0.6 on 2024-06-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegosMax', '0023_remove_juego_precioclp'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='precio',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
