# Generated by Django 5.0.6 on 2024-06-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegosMax', '0027_alter_juego_descripcionextensa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='img_url',
            field=models.CharField(default='', max_length=20),
        ),
    ]
