# Generated by Django 5.0.6 on 2024-06-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegosMax', '0028_alter_trailer_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='orden',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
